copy index.dos index.htm
echo file:aneta.ra > aneta.rpm
echo file:berna.ra > berna.rpm
echo file:davisa.ra > davisa.rpm
echo file:farleya.ra > farleya.rpm
echo file:hughesa.ra > hughesa.rpm
echo file:isaaka.ra > isaaka.rpm
echo file:jenesa.ra > jenesa.rpm
echo file:lebowa.ra > lebowa.rpm
echo file:lindowa.ra > lindowa.rpm
echo file:nandoa.ra > nandoa.rpm
echo file:shera.ra > shera.rpm
echo file:standa.ra > standa.rpm
echo file:stouga.ra > stouga.rpm
echo file:worldsa.ra > worldsa.rpm
echo file:anet.rm > anet.rpm
echo file:bern.rm > bern.rpm
echo file:davis.rm > davis.rpm
echo file:farley.rm > farley.rpm
echo file:hughes.rm > hughes.rpm
echo file:isaak.rm > isaak.rpm
echo file:itv.rm > itv.rpm
echo file:jenes.rm > jenes.rpm
echo file:lebow.rm > lebow.rpm
echo file:lindow.rm > lindow.rpm
echo file:nando.rm > nando.rpm
echo file:sher.rm > sher.rpm
echo file:smarr28.rm > smarr28.rpm
echo file:smarr56.rm > smarr56.rpm
echo file:stand.rm > stand.rpm
echo file:stoug.rm > stoug.rpm
echo file:worlds.rm > worlds.rpm
